ARG IMAGE_LOCATION=gobdo/odoo-gob
ARG ODOO_VERSION=14.0
FROM ${IMAGE_LOCATION}:${ODOO_VERSION}

ARG ODOO_VERSION
ENV ODOO_EXTRA_ADDONS /mnt/extra-addons
ENV ODOO_VERSION ${ODOO_VERSION}

USER root

RUN sudo mkdir -p ${ODOO_EXTRA_ADDONS}

COPY . ${ODOO_EXTRA_ADDONS}

RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends build-essential \
    && find ${ODOO_EXTRA_ADDONS} -name 'requirements.txt' -exec pip3 --no-cache-dir install -r {} \; \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

RUN sudo chown -R 1000:1000 ${ODOO_EXTRA_ADDONS}

RUN if [ "${ODOO_VERSION}" = "14.0" ]; then \
    cd /opt/odoo && \
    curl https://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/64772.patch | git apply - && \
    curl https://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/69429.patch | git apply - && \
    git status; \
    fi

# Odoo Configuration file variables
ARG ADMIN_PASSWORD
ENV ADMIN_PASSWORD ${ADMIN_PASSWORD}
ARG PGHOST
ENV PGHOST ${PGHOST}
ARG PGUSER
ENV PGUSER ${PGUSER}
ARG PGPORT
ENV PGPORT ${PGPORT}
ARG PGPASSWORD
ENV PGPASSWORD ${PGPASSWORD}
ARG HTTP_INTERFACE
ENV HTTP_INTERFACE ${HTTP_INTERFACE}
ARG HTTP_PORT
ENV HTTP_PORT ${HTTP_PORT}
ARG DBFILTER
ENV DBFILTER ${DBFILTER}
ARG DBNAME
ENV DBNAME ${DBNAME}
ARG SERVER_WIDE_MODULES
ENV SERVER_WIDE_MODULES ${SERVER_WIDE_MODULES}

# 
ARG EXTRA_MODULES
ENV EXTRA_MODULES ${EXTRA_MODULES}

# camptocamp variables
ARG RUNNING_ENV
ENV RUNNING_ENV ${RUNNING_ENV}
ARG ODOO_SESSION_REDIS
ENV ODOO_SESSION_REDIS ${ODOO_SESSION_REDIS}
ARG ODOO_SESSION_REDIS_HOST
ARG ODOO_SESSION_REDIS_PREFIX
ENV ODOO_SESSION_REDIS_PREFIX ${ODOO_SESSION_REDIS_PREFIX}
ENV ODOO_SESSION_REDIS_HOST ${ODOO_SESSION_REDIS_HOST}
ARG ODOO_LOGGING_JSON
ENV ODOO_LOGGING_JSON ${ODOO_LOGGING_JSON}
ARG AWS_HOST
ENV AWS_HOST ${AWS_HOST}
ARG AWS_REGION
ENV AWS_REGION ${AWS_REGION}
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ARG AWS_BUCKETNAME
ENV AWS_BUCKETNAME ${AWS_BUCKETNAME}
ARG AWS_BUCKETNAME_UNSTRUCTURED
ENV AWS_BUCKETNAME_UNSTRUCTURED ${AWS_BUCKETNAME_UNSTRUCTURED}

USER 1000
