name: Clean Deployment

on:
  pull_request:
    branches:
      - "[0-9]+.0"
    types: [ closed ]

jobs:
  delete:
    name: GKE Delete Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v3.x

      - name: Download deployment artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: tests.yaml
          name: deployment-${{ env.GITHUB_HEAD_REF_SLUG }}

      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
          credentials: ${{ secrets.GAR_JSON_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Remove the Docker image from the GKE cluster
      - name: Remove Deployment
        continue-on-error: true
        run: |
          kubectl delete -f deployment.yaml
